name: live_activity_flutter
description: Live activity plugin for flutter.
version: 0.0.1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.5
  app_group_directory: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
flutter:
  plugin:
    platforms:
      ios:
        pluginClass: LiveActivityFlutterPlugin
